import { theme } from "../theme";

export const styles: Record<string, React.CSSProperties> = {
  card: {
    background: theme.cardBg,
    borderRadius: 14,
    padding: 10,
    border: `1px solid ${theme.textFaint}`,
  },
  iconwrapper: {
    padding: 10,
    background: theme.bg,
    borderRadius: 14,
  },
  pageWrap: {
    display: "grid",
    gridTemplateColumns: "170px 1fr 170px",
    gap: 32,
    maxWidth: 1304,
    margin: "0 auto",
    padding: "16px 24px",
    alignItems: "start",
  },
  sideColumn: {
    position: "sticky",
    top: 72,
    display: "flex",
    flexDirection: "column",
    gap: 5,
    minWidth: 0,
  },
  sideNav: {
    borderRadius: 20,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  sideNavItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    textAlign: "left",
    background: theme.cardBg,
    border: `1px solid ${theme.textFaint}`,
    padding: "8px 12px",
    borderRadius: 20,
    color: theme.textFaint,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    whiteSpace: "nowrap",
  },
  page: { flex: 1, minWidth: 0 },
  section: { marginTop: 32 },
  mysteryOuterCard: {
    background: theme.cardBg,
    borderRadius: 20,
    padding: 20,
    border: `1px solid ${theme.textFaint}`,
    marginBottom: 32,
  },
  killerCard: {
    display: "flex",
    alignItems: "center",
    gap: 30,
    flexWrap: "wrap",
    background: theme.cardBg,
    borderRadius: 12,
    padding: 8,
    marginBottom: 32,
    border: `1px solid ${theme.textFaint}`,
  },
  killerPhotoWrap: {
    width: 130,
    height: 130,
    borderRadius: 12,
    border: `1px solid ${theme.cardBorder}`,
    background: theme.inputBg,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    flexShrink: 0,
  },
  killerPhotoImg: { width: "100%", height: "100%", objectFit: "cover" },
  killerPhotoWrapWrong: {
    background: theme.primary,
    borderColor: theme.primary,
  },
  guessArea: {
    flex: 1,
    minWidth: 240,
    paddingTop: 4,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: 8,
  },
  checklist: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px 20px",
  },
  checklistItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    color: theme.textMuted,
    fontSize: 14,
    fontWeight: 500,
  },
  checkCircle: {
    width: 26,
    height: 26,
    borderRadius: "50%",
    background: theme.bg,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  checkCircleDone: {
    background: theme.success,
    borderColor: theme.success,
  },
  guessRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  guessDropdownWrap: {
    position: "relative",
    flex: 1,
    minWidth: 180,
    maxWidth: 300,
  },
  guessDropdownTrigger: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: theme.inputBg,
    border: `1px solid ${theme.inputBorder}`,
    borderRadius: 20,
    color: theme.text,
    padding: "6px 12px",
    fontSize: 14,
    fontFamily: "inherit",
    boxSizing: "border-box",
  },
  guessDropdownAvatar: {
    width: 22,
    height: 22,
    borderRadius: "50%",
    background: theme.cardBg,
    border: `1px solid ${theme.inputBorder}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    flexShrink: 0,
  },
  guessDropdownAvatarImg: { width: "100%", height: "100%", objectFit: "cover" },
  guessDropdownLabel: {
    flex: 1,
    textAlign: "left",
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
  },
  guessDropdownList: {
    position: "absolute",
    top: "calc(100% + 6px)",
    left: 0,
    right: 0,
    display: "flex",
    flexDirection: "column",
    gap: 2,
    background: theme.cardBg,
    border: `1px solid ${theme.textFaint}`,
    borderRadius: 14,
    padding: 6,
    boxShadow: "0 8px 20px rgba(0,0,0,0.15)",
    zIndex: 20,
    maxHeight: 260,
    overflowY: "auto",
  },
  guessDropdownOption: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "none",
    border: "none",
    borderRadius: 10,
    padding: "6px 8px",
    fontSize: 14,
    fontFamily: "inherit",
    color: theme.text,
    textAlign: "left",
    cursor: "pointer",
  },
  guessBtn: {
    background: theme.textFaint,
    color: theme.primaryText,
    border: `1px solid ${theme.textFaint}`,
    borderRadius: 20,
    padding: "8px 14px",
    fontWeight: 700,
    fontSize: 15,
    cursor: "pointer",
  },
  guessResult: {
    margin: 0,
    fontSize: 12,
    fontWeight: 400,
  },
  sectionTitle: {
    fontFamily: theme.fontSerif,
    fontSize: 28,
    fontWeight: 700,
    color: theme.textFaint,
    marginBottom: 2,
    marginTop: 0,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    columnGap: 14,
  },
  // Holds the Ledtrådar card's status circles in its top-right corner.
  ledtradarTabCircles: {
    position: "absolute",
    top: 12,
    right: 12,
    zIndex: 2,
  },
  ledtradarTabCircle: {
    width: 26,
    height: 26,
    borderRadius: "50%",
    background: theme.bg,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  sortGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))",
    gap: 16,
  },
  sortBucket: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    marginBottom: 14,
    minHeight: 160,
    background: theme.inputBg,
    // Longhands, not `border`: sortBucketOver overrides borderColor, and
    // React warns when a shorthand and its longhands are mixed on rerender.
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: theme.inputBorder,
    borderRadius: 12,
    padding: 14,
    transition: "border-color 0.15s, background 0.15s",
  },
  sortBucketOver: {
    borderColor: theme.textFaint,
    borderStyle: "solid",
    background: theme.inputBg,
  },
  sortBucketHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  sortBucketHeaderLeft: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  sortBucketAvatar: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    background: theme.inputBg,
    border: `1px solid ${theme.inputBorder}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    flexShrink: 0,
  },
  sortBucketAvatarImg: { width: "100%", height: "100%", objectFit: "cover" },
  sortBucketName: {
    fontSize: 13,
    fontWeight: 700,
    color: theme.text,
  },
  sortItemList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    flex: 1,
  },
  sortItemListRow: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    flex: 1,
  },
  sortItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: theme.inputBg,
    border: `1px solid ${theme.inputBorder}`,
    borderRadius: 8,
    padding: "6px 10px",
    cursor: "grab",
  },
  sortItemImage: {
    width: 24,
    height: 24,
    borderRadius: 6,
    background: theme.cardBg,
    border: `1px solid ${theme.inputBorder}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    flexShrink: 0,
  },
  sortItemImageImg: { width: "100%", height: "100%", objectFit: "cover" },
  sortItemTitle: {
    fontSize: 13,
    color: theme.text,
  },
  cardNameRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  badge: {
    fontSize: 11,
    padding: "2px 8px",
    borderRadius: 20,
    color: theme.primaryText,
    textTransform: "capitalize" as const,
  },
  victimCard: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    background: theme.cardBg,
    borderRadius: 12,
    padding: 24,
    border: `1px solid ${theme.textFaint}`,
  },
  cardCheckBtn: {
    position: "absolute",
    top: 12,
    right: 12,
    background: "none",
    border: 0,
    outline: 0,
    padding: 0,
  },
  cardCheckCircle: {
    width: 26,
    height: 26,
    borderRadius: 18,
    background: theme.bg,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  cardCheckCircleDone: {
    background: theme.success,
    borderColor: theme.success,
  },
  victimHeader: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    textAlign: "left",
    gap: 16,
    marginBottom: 20,
  },
  victimPhoto: {
    width: 100,
    maxWidth: "100%",
    aspectRatio: "1 / 1",
    borderRadius: 10,
    background: theme.inputBg,
    border: `1px solid ${theme.inputBorder}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    flexShrink: 0,
  },
  victimPhotoImg: { width: "100%", height: "100%", objectFit: "cover" },
  victimName: {
    fontSize: 20,
    fontWeight: 700,
    color: theme.text,
    marginBottom: 4,
  },
  victimDesc: {
    fontSize: 13,
    color: theme.textMuted,
    margin: 0,
    lineHeight: 1.5,
  },
  investigationSection: {
    flex: 1,
    marginTop: 16,
    paddingTop: 14,
    borderTop: `1px solid ${theme.divider}`,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  compilationBtn: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    marginTop: "8px",
    alignSelf: "flex-end",
    background: theme.textFaint,
    color: theme.primaryText,
    border: `1px solid ${theme.textFaint}`,
    borderRadius: 20,
    padding: "8px 16px 8px 20px",
    fontWeight: 700,
    fontSize: 13,
    cursor: "pointer",
  },
  investigationTitle: {
    margin: 0,
    fontSize: 13,
    fontWeight: 700,
    color: theme.textFaint,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  investigationSub: {
    display: "flex",
    padding: "6px 6px 12px 12px",
    background: theme.bg,
    flexDirection: "column",
    gap: 4,
  },
  investigationSubtitle: {
    margin: 0,
    fontSize: 11,
    fontWeight: 700,
    color: theme.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  subsectionHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  subCheckBtn: {
    background: "none",
    border: "none",
    outline: "none",
    padding: 0,
    cursor: "pointer",
    flexShrink: 0,
  },
  subCheckCircle: {
    width: 18,
    height: 18,
    borderRadius: "50%",
    background: theme.cardBg,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  subCheckCircleDone: {
    background: theme.success,
    borderColor: theme.success,
  },
  investigationText: {
    margin: 0,
    fontSize: 13,
    color: theme.textMuted,
    lineHeight: 1.5,
  },
  // Fixed size (the desktop side column's width) so the timer doesn't
  // shrink on narrow screens, where it shares a row with the section nav.
  gameStartBtn: {
    width: 192,
    flexShrink: 0,
    boxSizing: "border-box",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: theme.textFaint,
    color: theme.primaryText,
    border: `1px solid ${theme.textFaint}`,
    borderRadius: 20,
    padding: "6px 0px",
    fontWeight: 700,
    fontFamily: "inherit",
    cursor: "pointer",
  },
  gameTimer: {
    width: 170,
    flexShrink: 0,
    boxSizing: "border-box",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: theme.textFaint,
    color: theme.primaryText,
    border: `1px solid ${theme.textFaint}`,
    borderRadius: 20,
    padding: "6px 0px",
    fontWeight: 700,
    fontFamily: "inherit",
    cursor: "pointer",
  },
  gameTimerValue: {
    fontFamily: theme.fontDigital,
    letterSpacing: 3,
    fontSize: 21,
    fontWeight: 600,
    color: theme.primaryText,
    fontVariantNumeric: "tabular-nums",
  },
};

// Styles that were duplicated verbatim (or near-verbatim) across two or
// more files. Each file that used to declare its own copy now imports
// this and either references a key directly, or spreads it with a small
// override where its version differs slightly from the rest.
export const sharedStyles: Record<string, React.CSSProperties> = {
  // Generic "cover" image fill, reused by every avatar/thumbnail/preview.
  imgCover: { width: "100%", height: "100%", objectFit: "cover" },

  // Admin CRUD list-page primitives (Scenes, Characters, Clues, Documents,
  // Evidence, Handelseforloppet, CaseTimeline).
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 28,
  },
  h1: { margin: 0, fontSize: 26, fontWeight: 700, color: theme.text },
  h1Bold: { margin: 0, fontSize: 35, fontWeight: 700, color: theme.text },
  name: { fontWeight: 600, fontSize: 16, color: theme.text },
  empty: {
    color: theme.textFaint,
    fontSize: 15,
    padding: "40px 0",
    textAlign: "center",
  },
  iconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: theme.textMuted,
    padding: 4,
    borderRadius: 4,
  },
  formActions: { display: "flex", gap: 10, justifyContent: "flex-end" },
  btn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: theme.primary,
    color: theme.primaryText,
    border: "none",
    borderRadius: 7,
    padding: "8px 16px",
    fontWeight: 700,
    fontSize: 14,
    cursor: "pointer",
  },
  btnSecondary: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: theme.secondaryBg,
    color: theme.secondaryText,
    border: "none",
    borderRadius: 7,
    padding: "8px 16px",
    fontWeight: 600,
    fontSize: 14,
    cursor: "pointer",
  },
  formCard: {
    background: theme.cardBg,
    border: `1px solid ${theme.cardBorder}`,
    borderRadius: 12,
    padding: 24,
    marginBottom: 28,
  },
  formTitle: {
    margin: "0 0 20px",
    fontSize: 18,
    fontWeight: 600,
    color: theme.accent,
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 16,
    marginBottom: 16,
  },
  formGridSingle: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 16,
    marginBottom: 16,
  },
  input: {
    width: "100%",
    background: theme.inputBg,
    border: `1px solid ${theme.inputBorder}`,
    borderRadius: 7,
    color: theme.text,
    padding: "8px 12px",
    fontSize: 14,
    fontFamily: "inherit",
    boxSizing: "border-box",
  },
  textarea: {
    width: "100%",
    background: theme.inputBg,
    border: `1px solid ${theme.inputBorder}`,
    borderRadius: 7,
    color: theme.text,
    padding: "8px 12px",
    fontSize: 14,
    fontFamily: "inherit",
    resize: "vertical",
    boxSizing: "border-box",
  },
  checkboxGroup: { display: "flex", flexWrap: "wrap", gap: 12 },
  checkLabel: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    color: theme.textMuted,
    fontSize: 14,
    cursor: "pointer",
  },
  revealedToggle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    cursor: "pointer",
    color: theme.textMuted,
    fontSize: 14,
    marginBottom: 20,
  },
  fileRow: { display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" },
  list: { display: "flex", flexDirection: "column", gap: 12 },
  card: {
    background: theme.cardBg,
    borderRadius: 10,
    padding: "16px 20px",
    border: `1px solid ${theme.cardBorder}`,
  },
  cardTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  cardMeta: { display: "flex", alignItems: "center", gap: 10 },
  cardActions: { display: "flex", gap: 8 },
  hiddenTag: {
    display: "flex",
    alignItems: "center",
    gap: 3,
    background: theme.secondaryBg,
    color: theme.textMuted,
    padding: "2px 8px",
    borderRadius: 20,
    fontSize: 11,
  },
  location: {
    fontSize: 12,
    color: theme.textMuted,
    background: theme.inputBg,
    padding: "2px 8px",
    borderRadius: 20,
  },
  tags: { display: "flex", gap: 6, flexWrap: "wrap" },
  tag: {
    fontSize: 12,
    background: theme.accentBg,
    color: theme.accent,
    padding: "2px 8px",
    borderRadius: 20,
  },
  desc: {
    fontSize: 13,
    color: theme.textMuted,
    margin: "0 0 10px",
    lineHeight: 1.5,
  },
  descCompact: {
    fontSize: 13,
    color: theme.textMuted,
    margin: "0 0 8px",
    lineHeight: 1.5,
  },
  // Legacy centered admin-page container (Scenes, Documents, Clues).
  pageNarrow: { maxWidth: 860, margin: "0 auto", padding: "32px 24px" },

  // Document/news viewer modal (Documents, Evidence).
  viewerHeader: {
    display: "flex",
    alignItems: "flex-start",
    gap: 14,
    marginBottom: 14,
  },
  viewerHeaderImg: {
    width: 56,
    height: 56,
    borderRadius: 8,
    objectFit: "cover",
    flexShrink: 0,
    border: `1px solid ${theme.inputBorder}`,
  },
  viewerTitle: {
    margin: "0 0 6px",
    fontSize: 18,
    fontWeight: 700,
    color: theme.text,
  },
  viewerDesc: {
    margin: 0,
    fontSize: 13,
    color: theme.textMuted,
    lineHeight: 1.5,
  },
  viewerFrame: {
    width: "100%",
    height: "70vh",
    background: theme.inputBg,
    borderRadius: 8,
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  viewerImg: { width: "100%", height: "100%", objectFit: "contain" },
  viewerIframe: { width: "100%", height: "100%", border: "none" },

  // Section-header "pill" pattern (CityMap, CaseTimeline): a rounded bar
  // with a checkmark circle at the front. justifyContent is set by each
  // caller since CityMap and CaseTimeline align it differently.
  pillHeaderBase: {
    display: "flex",
    alignItems: "center",
    marginBottom: 8,
    flexWrap: "wrap",
    background: theme.cardBg,
    border: `1px solid ${theme.textFaint}`,
    padding: "8px 8px",
    borderRadius: 30,
    gap: 8,
  },
  pillCheckCircle: {
    width: 26,
    height: 26,
    borderRadius: "50%",
    background: theme.bg,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  pillCheckCircleDone: {
    background: theme.success,
    borderColor: theme.success,
  },

  // Character detail pages (CharacterInvestigate, Compilation).
  pagePadded: { minWidth: 0, paddingBottom: 32 },
  detailBackBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "none",
    border: "none",
    color: theme.accent,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    padding: 0,
    marginBottom: 20,
  },
  detailHeader: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    marginBottom: 24,
  },
  detailPhoto: {
    width: 72,
    height: 72,
    borderRadius: "50%",
    background: theme.inputBg,
    border: `1px solid ${theme.inputBorder}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    flexShrink: 0,
  },
  detailCard: {
    background: theme.cardBg,
    border: `1px solid ${theme.cardBorder}`,
    borderRadius: 12,
    padding: 24,
  },
};
