export const theme = {
  // Warm, vintage case-file palette — 1950s Swedish "raggare" party gone wrong,
  // not a cold corporate gray/purple.
  bg: "#f6f2ea",
  cardBg: "#fffdf8",
  cardBorder: "#e4dcc9",
  inputBg: "#faf7f0",
  inputBorder: "#d9d0bb",
  divider: "#ece3d1",
  text: "#1a1611",
  textMuted: "#2a2419",
  textFaint: "#3d372c",
  accent: "#6b4a2f",
  accentBg: "#f2e8dc",
  primary: "#a40000",
  primaryText: "#ffffff",
  success: "#2e7d46",
  secondaryBg: "#f2e8dc",
  secondaryText: "#6b4a2f",
  fontSerif: "'Cormorant Garamond', serif",
  fontDisplay: "'Great Vibes', cursive",
  fontAccent: "'Creepster', cursive",
  fontDigital: "'VT323', monospace",
  roleColors: {
    suspect: "#b5541c",
    victim: "#a40000",
    detective: "#2f5f77",
    witness: "#4f8f6a",
  } as Record<string, string>,
  roleOrder: {
    detective: 0,
    victim: 1,
    suspect: 2,
    witness: 3,
  } as Record<string, number>,
  roleLabels: {
    suspect: "Misstänkt",
    victim: "Offer",
    detective: "Detektiv",
    witness: "Vittne",
  } as Record<string, string>,
};
